# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(549, 478)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setMouseTracking(False)
        self.centralwidget.setAutoFillBackground(True)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 4, 1, 1, 1)
        self.calcDisplay = QtWidgets.QLabel(self.centralwidget)
        self.calcDisplay.setEnabled(True)
        self.calcDisplay.setMaximumSize(QtCore.QSize(1024, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.calcDisplay.setFont(font)
        self.calcDisplay.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calcDisplay.setAutoFillBackground(True)
        self.calcDisplay.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calcDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.calcDisplay.setLineWidth(2)
        self.calcDisplay.setTextFormat(QtCore.Qt.RichText)
        self.calcDisplay.setScaledContents(True)
        self.calcDisplay.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calcDisplay.setWordWrap(False)
        self.calcDisplay.setObjectName("calcDisplay")
        self.gridLayout_2.addWidget(self.calcDisplay, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(80, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.calcDisplayRes = QtWidgets.QLabel(self.centralwidget)
        self.calcDisplayRes.setEnabled(True)
        self.calcDisplayRes.setMaximumSize(QtCore.QSize(1024, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri Light")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.calcDisplayRes.setFont(font)
        self.calcDisplayRes.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.calcDisplayRes.setAutoFillBackground(True)
        self.calcDisplayRes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.calcDisplayRes.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.calcDisplayRes.setLineWidth(2)
        self.calcDisplayRes.setTextFormat(QtCore.Qt.RichText)
        self.calcDisplayRes.setScaledContents(True)
        self.calcDisplayRes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.calcDisplayRes.setWordWrap(False)
        self.calcDisplayRes.setObjectName("calcDisplayRes")
        self.gridLayout_2.addWidget(self.calcDisplayRes, 2, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 3, 2, 1, 1)
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setObjectName("Logo")
        self.gridLayout_2.addWidget(self.Logo, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(9, -1, -1, -1)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.btn5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5.setObjectName("btn5")
        self.gridLayout.addWidget(self.btn5, 4, 2, 1, 1)
        self.btnSqrt = QtWidgets.QPushButton(self.centralwidget)
        self.btnSqrt.setObjectName("btnSqrt")
        self.gridLayout.addWidget(self.btnSqrt, 0, 2, 1, 1)
        self.btn0 = QtWidgets.QPushButton(self.centralwidget)
        self.btn0.setObjectName("btn0")
        self.gridLayout.addWidget(self.btn0, 6, 2, 1, 1)
        self.btnFactorial = QtWidgets.QPushButton(self.centralwidget)
        self.btnFactorial.setFlat(False)
        self.btnFactorial.setObjectName("btnFactorial")
        self.gridLayout.addWidget(self.btnFactorial, 0, 1, 1, 1)
        self.btnNeg = QtWidgets.QPushButton(self.centralwidget)
        self.btnNeg.setObjectName("btnNeg")
        self.gridLayout.addWidget(self.btnNeg, 6, 1, 1, 1)
        self.btnEq = QtWidgets.QPushButton(self.centralwidget)
        self.btnEq.setObjectName("btnEq")
        self.gridLayout.addWidget(self.btnEq, 6, 4, 1, 1)
        self.btnBackspace = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackspace.setObjectName("btnBackspace")
        self.gridLayout.addWidget(self.btnBackspace, 1, 3, 1, 1)
        self.btn4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4.setObjectName("btn4")
        self.gridLayout.addWidget(self.btn4, 4, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)
        self.btn3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3.setObjectName("btn3")
        self.gridLayout.addWidget(self.btn3, 5, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem5, 6, 5, 1, 1)
        self.btn8 = QtWidgets.QPushButton(self.centralwidget)
        self.btn8.setObjectName("btn8")
        self.gridLayout.addWidget(self.btn8, 3, 2, 1, 1)
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setObjectName("btn1")
        self.gridLayout.addWidget(self.btn1, 5, 1, 1, 1)
        self.btnDivByX = QtWidgets.QPushButton(self.centralwidget)
        self.btnDivByX.setObjectName("btnDivByX")
        self.gridLayout.addWidget(self.btnDivByX, 0, 4, 1, 1)
        self.btnDiv = QtWidgets.QPushButton(self.centralwidget)
        self.btnDiv.setObjectName("btnDiv")
        self.gridLayout.addWidget(self.btnDiv, 1, 4, 1, 1)
        self.btn6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn6.setObjectName("btn6")
        self.gridLayout.addWidget(self.btn6, 4, 3, 1, 1)
        self.btnMult = QtWidgets.QPushButton(self.centralwidget)
        self.btnMult.setObjectName("btnMult")
        self.gridLayout.addWidget(self.btnMult, 3, 4, 1, 1)
        self.btnExpon = QtWidgets.QPushButton(self.centralwidget)
        self.btnExpon.setObjectName("btnExpon")
        self.gridLayout.addWidget(self.btnExpon, 0, 3, 1, 1)
        self.btnReset = QtWidgets.QPushButton(self.centralwidget)
        self.btnReset.setObjectName("btnReset")
        self.gridLayout.addWidget(self.btnReset, 1, 2, 1, 1)
        self.btnPoint = QtWidgets.QPushButton(self.centralwidget)
        self.btnPoint.setObjectName("btnPoint")
        self.gridLayout.addWidget(self.btnPoint, 6, 3, 1, 1)
        self.btnPlus = QtWidgets.QPushButton(self.centralwidget)
        self.btnPlus.setObjectName("btnPlus")
        self.gridLayout.addWidget(self.btnPlus, 5, 4, 1, 1)
        self.btnMinus = QtWidgets.QPushButton(self.centralwidget)
        self.btnMinus.setObjectName("btnMinus")
        self.gridLayout.addWidget(self.btnMinus, 4, 4, 1, 1)
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setObjectName("btn2")
        self.gridLayout.addWidget(self.btn2, 5, 2, 1, 1)
        self.btn9 = QtWidgets.QPushButton(self.centralwidget)
        self.btn9.setObjectName("btn9")
        self.gridLayout.addWidget(self.btn9, 3, 3, 1, 1)
        self.btn7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn7.setObjectName("btn7")
        self.gridLayout.addWidget(self.btn7, 3, 1, 1, 1)
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setObjectName("btnDelete")
        self.gridLayout.addWidget(self.btnDelete, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        Calculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Calculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 549, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        Calculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Calculator)
        self.statusbar.setObjectName("statusbar")
        Calculator.setStatusBar(self.statusbar)
        self.actionPolozka1 = QtWidgets.QAction(Calculator)
        self.actionPolozka1.setObjectName("actionPolozka1")
        self.actionAuto_i = QtWidgets.QAction(Calculator)
        self.actionAuto_i.setObjectName("actionAuto_i")
        self.menuMenu.addAction(self.actionPolozka1)
        self.menuMenu.addAction(self.actionAuto_i)
        self.menubar.addAction(self.menuMenu.menuAction())

        #after pressing one of the number buttons their respective number will be appended
        #to the end of the string to be shown and parsed
        self.btn0.clicked.connect(lambda: self.setStr('0'))
        self.btn1.clicked.connect(lambda: self.setStr('1'))
        self.btn2.clicked.connect(lambda: self.setStr('2'))
        self.btn3.clicked.connect(lambda: self.setStr('3'))
        self.btn4.clicked.connect(lambda: self.setStr('4'))
        self.btn5.clicked.connect(lambda: self.setStr('5'))
        self.btn6.clicked.connect(lambda: self.setStr('6'))
        self.btn7.clicked.connect(lambda: self.setStr('7'))
        self.btn8.clicked.connect(lambda: self.setStr('8'))
        self.btn9.clicked.connect(lambda: self.setStr('9'))

        #After pressing the operation button their respective symbol will be appended at the end of
        #the string to be shown and parsed
        self.btnPlus.clicked.connect(lambda: self.setStr('+'))
        self.btnMinus.clicked.connect(lambda: self.setStr('-'))
        self.btnMult.clicked.connect(lambda: self.setStr('*'))
        self.btnDiv.clicked.connect(lambda: self.setStr('/'))
        self.btnFactorial.clicked.connect(lambda: self.setStr('!'))
        self.btnSqrt.clicked.connect(lambda: self.setStr('$'))
        self.btnExpon.clicked.connect(lambda: self.setStr('^'))
        self.btnPoint.clicked.connect(lambda: self.setStr('.'))


        #clicking the operation buttons will call their function
        self.btnNeg.clicked.connect(self.negate) #appends "-" at the start of the string
        self.btnBackspace.clicked.connect(self.backSpace) #removes the last entered value
        self.btnDelete.clicked.connect(self.deleteList) #deletes the last entered input
        self.btnReset.clicked.connect(self.resetList) #resets the entire calculation

        self.btnEq.clicked.connect(self.calculate) #calls the parser to calculate value of expression

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

        self.listToParse = list() #list that will be sent to the parser
        self.listToShow = list()  #list that will be shown to the user
        self.lastRes = list       #list containing the previus result

    def update(self):
        temp = ''.join(self.listToShow)
        self.calcDisplay.setText(temp)

    def deleteList(self):
        self.listToParse = []
        self.listToShow = []
        self.update()

    def resetList(self):
        self.lastRes = []
        self.deleteList()

    def backSpace(self):
        self.listToParse = self.listToParse[:-1]
        self.listToShow = self.listToShow[:-1]
        self.update()

    def negate(self):
        self.listToParse.insert(0, '-')
        self.listToShow.insert(0, '-')
        self.update()

    def calculate(self):
        #print(self.listToParse)
        self.lastRes = lib.evaluate(self.listToParse)
        var = ''.join(self.lastRes)
        self.deleteList()
        self.calcDisplayRes.setText(var)

    def setStr(self, a):
        self.listToParse.append(a)
        if a == "$":
            self.listToShow.append("√")
        else:
            self.listToShow.append(a)

        self.update()

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "MainWindow"))
        self.calcDisplay.setText(_translate("Calculator", "0"))
        self.calcDisplayRes.setText(_translate("Calculator", "0"))
        pixmap = QPixmap("logo.png")
        pixmap = pixmap.scaledToWidth(200)
        self.Logo.setPixmap(pixmap)
        self.Logo.show()
        self.btn5.setText(_translate("Calculator", "5"))
        self.btn5.setShortcut(_translate("Calculator", "5"))
        self.btnSqrt.setText(_translate("Calculator", "√"))
        self.btn0.setText(_translate("Calculator", "0"))
        self.btn0.setShortcut(_translate("Calculator", "0"))
        self.btnFactorial.setText(_translate("Calculator", "Factorial !"))
        self.btnNeg.setText(_translate("Calculator", "Neg"))
        self.btnEq.setText(_translate("Calculator", "="))
        self.btnEq.setShortcut(_translate("Calculator", "="))
        self.btnBackspace.setText(_translate("Calculator", "Backspace"))
        self.btnBackspace.setShortcut(_translate("Calculator", "Backspace"))
        self.btn4.setText(_translate("Calculator", "4"))
        self.btn4.setShortcut(_translate("Calculator", "4"))
        self.btn3.setText(_translate("Calculator", "3"))
        self.btn3.setShortcut(_translate("Calculator", "3"))
        self.btn8.setText(_translate("Calculator", "8"))
        self.btn8.setShortcut(_translate("Calculator", "8"))
        self.btn1.setText(_translate("Calculator", "1"))
        self.btn1.setShortcut(_translate("Calculator", "1"))
        self.btnDivByX.setText(_translate("Calculator", "1/x"))
        self.btnDiv.setText(_translate("Calculator", "/"))
        self.btnDiv.setShortcut(_translate("Calculator", "/"))
        self.btn6.setText(_translate("Calculator", "6"))
        self.btn6.setShortcut(_translate("Calculator", "6"))
        self.btnMult.setText(_translate("Calculator", "*"))
        self.btnMult.setShortcut(_translate("Calculator", "*"))
        self.btnExpon.setText(_translate("Calculator", "X^n"))
        self.btnReset.setText(_translate("Calculator", "Reset"))
        self.btnPoint.setText(_translate("Calculator", "."))
        self.btnPoint.setShortcut(_translate("Calculator", "., ,"))
        self.btnPlus.setText(_translate("Calculator", "+"))
        self.btnPlus.setShortcut(_translate("Calculator", "+"))
        self.btnMinus.setText(_translate("Calculator", "-"))
        self.btnMinus.setShortcut(_translate("Calculator", "-"))
        self.btn2.setText(_translate("Calculator", "2"))
        self.btn2.setShortcut(_translate("Calculator", "2"))
        self.btn9.setText(_translate("Calculator", "9"))
        self.btn9.setShortcut(_translate("Calculator", "9"))
        self.btn7.setText(_translate("Calculator", "7"))
        self.btn7.setShortcut(_translate("Calculator", "7"))
        self.btnDelete.setText(_translate("Calculator", "Delete"))
        self.btnDelete.setShortcut(_translate("Calculator", "Del"))
        self.menuMenu.setTitle(_translate("Calculator", "Menu"))
        self.actionPolozka1.setText(_translate("Calculator", "Nápověda"))
        self.actionAuto_i.setText(_translate("Calculator", "Autoři"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())

